# Generated by Django 3.2.12 on 2022-02-18 10:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_phone', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999) 999-9999'. Up to 15 digits allowed", regex='^\\s*(?:\\+?(\\d{1,3}))?[- (]*(\\d{3})[- )]*(\\d{3})[- ]*(\\d{4})(?: *[x/#]{1}(\\d+))?\\s*$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(default=3291, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats 12345 or 12345-1234', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')])),
                ('country', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
