# Generated by Django 3.2.12 on 2022-02-21 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
