# Generated by Django 3.2.12 on 2022-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
