# Generated by Django 3.2.12 on 2022-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_by',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
