# Generated by Django 3.2.12 on 2022-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220221_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ref_code',
            new_name='my_ref_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_count',
        ),
        migrations.AddField(
            model_name='user',
            name='my_ref_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
