# Generated by Django 3.2.12 on 2022-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_my_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_ref_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
